### ISSUE TITLE
&l seems to be cancelling &m

### ISSUE THREAD

**Issue by OpenSource03** [SnowFireWolf/minecraft-motd-parser#2]
Hello there!

As you can see from the following example
![Screenshot 2022-06-16 at 19 55 17](https://user-images.githubusercontent.com/29690431/174135185-39647d5b-ad7c-4972-b2db-855e35690448.png)

&l seems to be cancelling &m. Here's the MOTD code (could not upload it as text as GitHub seems to be removing backspaces):
![Screenshot 2022-06-16 at 19 57 21](https://user-images.githubusercontent.com/29690431/174135525-3f67d18d-befa-48b3-b7d3-400de6ec93b4.png)

The following MOTD code should result into the following:
![Screenshot 2022-06-16 at 19 58 25](https://user-images.githubusercontent.com/29690431/174135690-38e1a041-068e-4d43-b54a-d7463b71392d.png)

You can check the result [here](https://mctools.org/motd-creator?text=%26r%26f++++++++++++++++%26r%269%26m%26l+++%26r%268%26m%26l%5B+%26r%26f+%26r%266%26lMineplex%26r%26f+%26r%26f%26lGames%26r%26f+%26r%268%26m%26l+%5D%26r%269%26m%26l+++%26r%26f%0A++++++++++++++++++++++++%26r%26e%26lSTATS+REVAMP%26r).

Please fix the issue above, otherwise, the project is amazing!

**Comment by SnowFireWolf** [comment]
Thanks 👍
I will find time to deal with it

**Comment by OpenSource03** [comment]
Additionally, it seems like it's impossible to do something like &a&l&n, because &n is overwriting &l. In Minecraft, it's possible to have both underline and bold, but here it doesn't seem to work, it's kinda related to the issue above.

**Comment by SnowFireWolf** [comment]
@OpenSource03 Hiii I fix this issue, you can review it.
