### ISSUE TITLE
When "sourceJson" include "short" type doesn't working

### ISSUE THREAD

**Issue by tuanzisama** [SnowFireWolf/minecraft-motd-parser#5]
When `motdParser.JSONToHtml` argument `sourceJson` include "short" type doesn't working.
当调用 `motdParser.JSONToHtml` 时传入的参数中包含 `short` 类型值，此内容将不会转换至 `HTML`。

Example: 
```json
{
  "extra":  
    [{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"life boost: "}, 
    {"italic":false,"color":"white","text":5}],
  "text":""
}
```
![image](https://user-images.githubusercontent.com/33369729/181918176-a9cefdfe-d687-4985-8cc2-08f0257927bc.png)

As you can see, In `motdParser.JSONToHtml`, when `text` is `short (number)` type, they doens't add into HTML.
如示例所见，调用  `motdParser.JSONToHtml` 并传入上面的示例 JSON，在HTML将不会正常显示`short (number)` 类型的 `5` 。

---
Is it possible to allow number value? 是否在此判断中可以允许number值？
![image](https://user-images.githubusercontent.com/33369729/181917813-6d73281e-08a2-4306-aed8-488a2e31e312.png)

**Comment by SnowFireWolf** [comment]
嗨 @tuanzisama 
感謝你的回報
我今天應該可以處理這個問題 👍

**Comment by tuanzisama** [comment]
谢谢，经过测试已没有问题。
Thanks, it's been tested without problems.
